### ISSUE TITLE
General review

### ISSUE THREAD

**Issue by akaszynski** [pyansys/ml-rl-cartpole#3]
- [x] Index needs to be cleaned up: https://github.com/pyansys/ml-rl-cartpole/pull/2
- [x] Add more info to the README. Done in #4
- [x] ~~We have a duplicate of the notebook and our documented notebook. Is there a way to merge this? If not, I'm fine with them being separate, but it will be harder to maintain.~~ We can work on this at a later date.
- [x] Add a breadcrumb trail to PyMAPDL. Done in #4
- [x] ~~Add a link to the notebook page (not the index) to https://mapdldocs.pyansys.com/user_guide/extended_examples/index.html~~ Moved to https://github.com/pyansys/pymapdl/issues/889
- [x] Add CI/CD for doc build. Done in #4
- [x] `docs_source` --> `doc`. Done in #4
